Part7
AalexxJjamess/PFMCPP_Project4 pull request #7
Opened 2020-09-05 14:12 UTC by AalexxJjamess

2020-09-05 17:19 UTC, matkatmusic requested changes
Did you compare your output with the expected output?

2020-09-05 17:19 UTC, matkatmusic commented on main.cpp
> +                if (static_cast<int>(rhs) == 0) // added this cast to prevent any warnings regarding floating point comparing with ==
you're missing `constexpr` here.  constexpr prevents the need for that cast.
- [ ] revise

2020-09-05 17:19 UTC, matkatmusic commented on main.cpp
> +        *value = *value + rhs;
```
*value += rhs;
```
it is `operator +=` after all...
- [ ] revise

2020-09-05 17:19 UTC, matkatmusic commented on main.cpp
> +        *value = *value - rhs;
```
*value -= rhs;
```
- [ ] revise

2020-09-05 17:19 UTC, matkatmusic commented on main.cpp
> +        *value = *value * rhs;
- [ ] revise

2020-09-05 17:19 UTC, matkatmusic commented on main.cpp
> +            }
This specialization is explicit for `Type == double`.  None of those `is_same` checks will ever be called because `Type` will never be `int`.
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic requested changes
Your coding style doesn't match the course coding style.  stop using an auto-formatter that doesn't match the course coding style.

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	using Type = ValueType;
- curly braces go on their own line.
- template and its argument should go on their own line:
```
template<class T>
struct Foo ...
```
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	}
since `value` is a unique_ptr now, you don't need to manually reset it.  When this class goes out of scope, the `value` member variable will be destroyed correctly, releasing the heap allocation correctly.
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	}
- What are these functions returning?   Make your return type obvious.  Put the `&` next to the return type, not next to the function name.
- Curly braces go on their own line
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +    Numeric& operator /=(const Type rhs)
This function should be templated.  its parameter should not be `Type`.  it should be `OtherType`. 
Think about what happens in this function when Type is `int`, vs. when you pass it a `double`. 
Specifically the pseudo-code line "if your parameter's type is also int... else if its less than epsilon"
That line indicates that your function argument doesn't have to match the class's template type.
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +            else if (rhs < std::numeric_limits<Type>::epsilon())
- [ ] revise, per above instructions

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +        else if (rhs < std::numeric_limits<Type>::epsilon())
- [ ] revise, per above instructions.

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	}
- indentation is not 4
- curly braces go on their own line.
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	}
- indentation is not 4
- curly braces go on their own line.
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	}
- indentation is not 4
- curly braces go on their own line.
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	}
- indentation is not 4
- curly braces go on their own line.
- [ ] revise

2020-09-06 18:48 UTC, matkatmusic commented on main.cpp
> +	}
- indentation is not 4
- curly braces go on their own line.
- [ ] revise

2020-09-09 05:15 UTC, matkatmusic requested changes
- [ ] fix the formatting.

2020-09-09 05:15 UTC, matkatmusic commented on main.cpp
> +        value = {std::make_unique<Type>(valueIn_)};
You don't need curly braces here to initialize `value`.  And you should be using the constructor's member initializer list to initialize `value`. 
 - [ ] revise

2020-09-09 05:15 UTC, matkatmusic commented on main.cpp
> +	}
you've got some weird indentation here.
- [ ] revise

2020-09-09 05:15 UTC, matkatmusic commented on main.cpp
> +            if constexpr (std::is_same<decltype(rhs), const int>::value)
instead of `decltype(rhs)`, just put `OtherType`.  `rhs` is an instance of `OtherType`.
- [ ] revise

2020-09-09 05:15 UTC, matkatmusic commented on main.cpp
> +            else if (rhs < std::numeric_limits<OtherType>::epsilon())
What happens if `OtherType` is `float`, and `rhs` is `-1.f`?
- [ ] revise

2020-09-09 05:15 UTC, matkatmusic commented on main.cpp
> +        else if (rhs < std::numeric_limits<OtherType>::epsilon())
- [ ] revise

2020-09-09 05:15 UTC, matkatmusic commented on main.cpp
> +	}
- [ ] fix the formatting.

2020-09-09 05:15 UTC, matkatmusic commented on main.cpp
> +	}
- [ ] fix the formatting.

2020-09-09 14:53 UTC, AalexxJjamess commented on main.cpp
> +	}
This is how it appears on my repl.it:
<img width="419" alt="Screenshot 2020-09-09 at 15 50 44" src="https://user-images.githubusercontent.com/49648572/92614685-3a0a2580-f2b4-11ea-8f66-7eb6677d6150.png">

2020-09-09 15:34 UTC, AalexxJjamess commented on main.cpp
> +            else if (rhs < std::numeric_limits<OtherType>::epsilon())
The function will still give the warning, i'll change it to if abs(rhs) < epsilon.

2020-09-09 15:37 UTC, AalexxJjamess commented on main.cpp
> +	}
<img width="625" alt="Screenshot 2020-09-09 at 16 37 23" src="https://user-images.githubusercontent.com/49648572/92620625-bef83d80-f2ba-11ea-8d4b-8e286127ff90.png">
Again, doesn't look like this on my end...

2020-09-11 02:37 UTC, matkatmusic approved these changes

2020-09-11 02:37 UTC, merged